rails/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'

  get "welcome/index"
  post "welcome/trigger_job"
  post "welcome/rake_job"

  # Defines the root path route ("/")
  # root "articles#index"
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def trigger_job
    HardJob.perform_async('bob', 5)
  end

  def rake_job
    RakeJob.perform_async('bob', 5)
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'pico.min.css' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/app/views/welcome/index.html.erb
<main class="container">

  <h1>Welcome</h1>

  <%= form_with url: welcome_trigger_job_path do |f| %>
  <%= f.submit 'Launch sample job' %>
  <% end %>

  <%= form_with url: welcome_rake_job_path do |f| %>
  <%= f.submit 'Launch Rake job' %>
  <% end %>

</main>